import { ArrowLeft, ArrowUpRight, Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Status } from '../data';

export function Button({ children, variant = 'primary', icon, onClick, type = 'button' }: { children: React.ReactNode; variant?: 'primary' | 'secondary' | 'quiet' | 'danger'; icon?: React.ReactNode; onClick?: () => void; type?: 'button' | 'submit' }) { return <button className={`button button-${variant}`} onClick={onClick} type={type}>{icon}{children}</button> }
export function MetricCard({ label, value, detail, tone = 'blue', to }: { label: string; value: string; detail: string; tone?: string; to?: string }) { const card = <div className={`metric-card metric-${tone}`}><div className="metric-top"><span>{label}</span><ArrowUpRight size={16} /></div><strong>{value}</strong><small>{detail}</small></div>; return to ? <Link to={to} className="metric-link">{card}</Link> : card }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }
export function StatusBadge({ status }: { status: Status | string }) { return <span className={`status status-${status.toLowerCase().replaceAll(' ', '-')}`}><span className="status-dot" />{status}</span> }
export function Detail({ label, value }: { label: string; value: string }) { return <div className="detail"><span>{label}</span><strong>{value}</strong></div> }
export function PanelTitle({ title, text, link, linkText }: { title: string; text: string; link?: string; linkText?: string }) { return <div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div>{link && <Link to={link} className="text-link">{linkText} <ArrowUpRight size={14} /></Link>}</div> }
export function Back({ to, label = 'Back' }: { to: string; label?: string }) { return <div className="back-link"><Link to={to}><ArrowLeft size={15} /> {label}</Link></div> }
export function Table({ children }: { children: React.ReactNode }) { return <section className="panel table-panel"><div className="table-scroll"><table>{children}</table></div></section> }
export function Toolbar({ search, setSearch, placeholder = 'Search by customer, quote or owner...' }: { search: string; setSearch: (value: string) => void; placeholder?: string }) { return <div className="toolbar"><div className="search"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={placeholder} /></div><button className="filter-button">Filters <span>2</span></button><select className="filter-select"><option>All statuses</option><option>Pending</option><option>Approved</option><option>Draft</option></select></div> }
export function WorkflowStep({ label, done, active }: { label: string; done?: boolean; active?: boolean }) { return <div className={`workflow-step ${done ? 'done' : ''} ${active ? 'active' : ''}`}><span>{done ? <Check size={13} /> : active ? <span /> : ''}</span>{label}</div> }
export function BillingLine({ name, detail, amount }: { name: string; detail: string; amount: string }) { return <div className="billing-line"><div className="product-badge">•</div><div><strong>{name}</strong><span>{detail}</span></div><strong>{amount}</strong></div> }
export function Activity({ title, detail, time }: { title: string; detail: string; time: string }) { return <div className="activity"><div className="activity-icon blue">•</div><div><strong>{title}</strong><span>{detail}</span></div><time>{time}</time></div> }
export function EmptyState({ title, detail }: { title: string; detail: string }) { return <div className="empty-state"><strong>{title}</strong><span>{detail}</span></div> }
